# Generated by Django 5.1.2 on 2024-11-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/models/')),
                ('size_option', models.CharField(choices=[('small', 'Pequeño'), ('medium', 'Medio'), ('large', 'Grande')], max_length=20)),
                ('quality_option', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
