# Generated by Django 5.1.2 on 2024-11-03 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_uploadedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='quality_option',
        ),
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='size_option',
        ),
    ]
